name: CD
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Heroku
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        # This will be used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        # Email that you use with heroku
        heroku_email: remi50avJ.C@live.fr
        # The appname to use for deploying/updating
        heroku_app_name: ${{ secrets.HEROKU_APP }}
        branch: master
        # usedocker: # optional, default is false
        # Type of heroku process (web, worker, etc). This option only makes sense when usedocker enabled
        # docker_heroku_process_type: # optional, default is web
        # A list of args to pass into the Docker build. This option only makes sense when usedocker enabled
        # docker_build_args: # optional
        procfile: # optional, default is 
          Procfile
        # When set to true this will attempt to rollback to the previous release if the healthcheck fails
        # rollbackonhealthcheckfailed: # optional, default is false
